name: registry.k8s.io.images
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login in Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker pull and push
        run: |
          docker pull gcr.io/distroless/static:nonroot
          docker tag  gcr.io/distroless/static:nonroot ghcr.io/khh403/static:nonroot
          docker push ghcr.io/khh403/static:nonroot
