name: registry.k8s.io.images
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login in Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker pull and push
        run: |
          docker pull gcr.io/distroless/static:nonroot
          docker tag  gcr.io/distroless/static:nonroot ghcr.io/khh403/distroless-static:nonroot
          docker push ghcr.io/khh403/distroless-static:nonroot
          
          docker pull golang:1.19
          docker tag  golang:1.19 ghcr.io/khh403/golang:1.19
          docker push ghcr.io/khh403/golang:1.19

          docker pull gcr.io/kaniko-project/executor:latest
          docker tag gcr.io/kaniko-project/executor:latest ghcr.io/khh403/kaniko-project/executor:latest
          docker push ghcr.io/khh403/kaniko-project/executor:latest
