name: registry.k8s.io.images
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCRIOTOKEN }}
      - name: Docker pull and push
        run: |
          docker pull registry.k8s.io/build-image/kube-cross:v1.28.0-go1.20.11-bullseye.0
          docker tag  registry.k8s.io/build-image/kube-cross:v1.28.0-go1.20.11-bullseye.0 ghcr.io/khh403/build-image/kube-cross:v1.28.0-go1.20.11-bullseye.0
          docker push ghcr.io/khh403/build-image/kube-cross:v1.28.0-go1.20.11-bullseye.0
