name: registry.k8s.io.images
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCRIOTOKEN }}
      - name: Docker pull and push
        run: |

          docker pull docker.io/hpcaitech/pytorch-cuda:2.1.0-12.1.0
          docker tag  docker.io/hpcaitech/pytorch-cuda:2.1.0-12.1.0 ghcr.io/khh403/hpcaitech/pytorch-cuda:2.1.0-12.1.0
          docker push ghcr.io/khh403/hpcaitech/pytorch-cuda:2.1.0-12.1.0
